=== decodelabs/chronos/schema/0.1/program.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://schema.decodelabs.com/chronos/0.1/program.json",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "The schema that this document should conform to.",
            "enum": [
                "https://schema.decodelabs.com/chronos/0.1/program.json",
                "../schema/0.1/program.json"
            ]
        },
        "id": {
            "$ref": "shared.json#id",
            "description": "The unique identifier for this program."
        },
        "name": {
            "type": "string",
            "description": "The name of the program."
        },
        "description": {
            "type": "string",
            "description": "A short description of what the program does."
        },
        "categories": {
            "type": "array",
            "description": "A list of IDs of categories that this program belongs to.",
            "items": {
                "$ref": "shared.json#id",
                "description": "The unique identifier for a category."
            }
        },
        "duration": {
            "type": "string",
            "description": "A string representation of the estimated time it will take to complete the program."
        },
        "priority": {
            "$ref": "shared.json#priority",
            "description": "A string representation of the priority of the program."
        },
        "steps": {
            "type": "array",
            "items": {
                "$ref": "step.json"
            }
        }
    },
    "required": [
        "id",
        "name",
        "description",
        "categories",
        "duration",
        "priority",
        "steps"
    ]
}

=== decodelabs/chronos/examples/artist-profile-setup.json
{
    "id": "artist-profile-setup",
    "name": "Artist Profile Setup",
    "description": "Get your artist profile in check - get your biography written, photos uploaded and best foot forward.",
    "categories": [ "profile", "setup" ],
    "duration": "1 week",
    "priority": "high",
    "steps": [ {
            "id": "select-profile",
            "priority": "critical",
            "actions": {
                "Profile.Select:$profile": { }
            }
        }, {
            "id": "choose-name",
            "priority": "medium",
            "duration": "2 hours",
            "actions": {
                "Profile.GenerateName": { }
            }
        }, {
            "id": "upload-avatar",
            "priority": "high",
            "duration": "1 hour",
            "actions": {
                "Profile.UploadAvatar": { }
            }
        }, {
            "id": "write-biography",
            "priority": "medium",
            "duration": "1 day",
            "actions": {
                "Profile.GenerateBiography": { }
            }
        }, {
            "id": "upload-photos",
            "await": {
                "select-profile": "5 days",
                "upload-avatar": null
            },
            "priority": "low",
            "duration": "1 hour",
            "actions": {
                "Profile.UploadPhotos": { }
            }
        } ]
}
